homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 16
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret pwd
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  - platform: mqtt
    state_topic: "/sensornode/livingroom/DHT/status"
    name: "Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity }}'
  - platform: mqtt
    state_topic: "/sensornode/livingroom/BMP/status"
    name: "Pressure"
    unit_of_measurement: "mpa"
    value_template: '{{ value_json.pressure }}'
  - platform: mqtt
    state_topic: "/sensornode/livingroom/BMP/status"
    name: "temperature"
    unit_of_measurement: "C"
    value_template: '{{ value_json.temp }}'
  - platform: mqtt
    state_topic: "/sensornode/bedroom/SHT/status"
    name: "Humidity bedroom"
    unit_of_measurement: "%"
    value_template: '{{ value_json.pressure }}'
  - platform: mqtt
    state_topic: "/sensornode/bedroom/SHT/status"
    name: "temp bedroom"
    unit_of_measurement: "C"
    value_template: '{{ value_json.temp }}'
  - platform: mqtt
    state_topic: "rf434/recv/alecto_ws1700/246"
    name: "outside humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity }}'
  - platform: mqtt
    state_topic: "rf434/recv/alecto_ws1700/246"
    name: "outside temp"
    unit_of_measurement: "C"
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: "rf434/recv/alecto_ws1700/246"
    name: "outside battery"
    unit_of_measurement: "%"
    value_template: '{{ value_json.battery }}'
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "C"
    value_template: '{{ value | multiply(0.001) }}'


binary_sensor:
  - platform: mqtt
    state_topic: "/sensornode/bedroom/RADAR/status"
    name: "movement bedroom"
    payload_on: 1
    payload_off: 0
    value_template: '{{ value_json.status }}'
  - platform: mqtt
    state_topic: "/sensornode/livingroom/PIR/status"
    name: "movement"
    payload_on: 1
    payload_off: 0
    value_template: '{{ value_json.status }}'
  - platform: mqtt
    state_topic: "/sensornode/livingroom/sound/status"
    name: "sound"
    payload_on: 1
    payload_off: 0
    value_template: '{{ value_json.status }}'
#  - platform: mqtt
#    state_topic: "rf434/recv/arctech_screen_old/18"
#    name: "door open"
#    payload_on: "down"
#    value_template: '{{ value_json.state }}'

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml

mqtt:
  broker: chip
  port: 1888
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_pwd

light:
  # these lights are setup with the 433MQTTBridge, which uses pilight json
  # disadvangate is that the state includes the unit number and is not distinguishable by topic
  - platform: mqtt_template
    name: kitchen
    command_topic: "rf434/send/arctech_switch"
    state_topic: "rf434/recv/arctech_switch/4860734"
    command_on_template: '{"id":4860734,"unit":0,"on":1}'
    command_off_template: '{"id":4860734,"unit":0,"off":1}'
    state_template: '{% if  value_json.unit == 0  %} {{ value_json.state }} {% endif %}'
  - platform: mqtt_template
    name: bookcase
    command_topic: "rf434/send/arctech_switch"
    state_topic: "rf434/recv/arctech_switch/4860734"
    command_on_template: '{"id":4860734,"unit":1,"on":1}'
    command_off_template: '{"id":4860734,"unit":1,"off":1}'
    state_template: '{% if  value_json.unit == 1  %} {{ value_json.state }} {% endif %}'
  - platform: mqtt_template
    name: couch
    command_topic: "rf434/send/arctech_switch"
    state_topic: "rf434/recv/arctech_switch/4860734"
    command_on_template: '{"id":4860734,"unit":2,"on":1}'
    command_off_template: '{"id":4860734,"unit":2,"off":1}'
    state_template: '{% if  value_json.unit == 2  %} {{ value_json.state }} {% endif %}'
  - platform: mqtt_template
    name: livingroom
    command_topic: "rf434/send/arctech_switch"
    state_topic: "rf434/recv/arctech_switch/10942094"
    command_on_template: '{"id":10942094,"unit":0,"on":1}'
    command_off_template: '{"id":10942094,"unit":0,"off":1}'
    state_template: '{% if  value_json.unit == 0  %} {{ value_json.state }} {% endif %}'
  - platform: mqtt_template
    name: ikea
    command_topic: "rf434/send/arctech_switch"
    state_topic: "rf434/recv/arctech_switch/10942094"
    command_on_template: '{"id":10942094,"unit":1,"on":1}'
    command_off_template: '{"id":10942094,"unit":1,"off":1}'
    state_template: '{% if  value_json.unit == 1  %} {{ value_json.state }} {% endif %}'
  - platform: mqtt_template
    name: table
    command_topic: "rf434/send/arctech_switch"
    state_topic: "rf434/recv/arctech_switch/10942094"
    command_on_template: '{"id":10942094,"unit":2,"on":1}'
    command_off_template: '{"id":10942094,"unit":2,"off":1}'
    state_template: '{% if  value_json.unit == 2  %} {{ value_json.state }} {% endif %}'
  - platform: mqtt_json
    name: lichtstraat
    state_topic: "home/rgb1"
    command_topic: "home/rgb1/set"
    brightness: true
    rgb: true
    optimistic: false
    qos: 0

script: !include scripts.yaml

device_tracker:
  - platform: luci
    host: 192.168.0.254
    username: !secret router_user
    password: !secret router_pwd
    track_new_devices: false
    interval_seconds: 12
    consider_home: 120

notify:
  - name: doorbell
    platform: smtp
    server: smtp.aol.com
    port: 587
    timeout: 15
    sender: !secret email
    encryption: starttls
    username: !secret email
    password: !secret emailpwd
    recipient:
      - erik.van.der.velden@gmail.com
    sender_name: DOORBELL
  - name: dog
    platform: command_line
    command: "aplay /home/homeassistant/Dog-barking-very-loudly.wav"
